server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/User/Documents/springprojects/celebrating-microservices-main/config-repo
          clone-on-start: true
