spring:
  application:
    name: auth-service
  config:
    import: "configserver:"
  datasource:
    url: jdbc:postgresql://localhost:5432/celebratedb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081
  servlet:
    context-path: /api/auth

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost

jwt:
  secret: your-secret-key-must-be-at-least-32-characters-long
  expiration: 86400000 # 24 hours

cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,HEAD
  allowed-headers: "*"
  exposed-headers: "*"
  allow-credentials: true
  max-age: 3600
