server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:"
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/celebratedb
    username: postgres
    password: postgres
    pool:
      initial-size: 5
      max-size: 20
      validation-query: SELECT 1
    properties:
      ssl: false
      sslMode: disable
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    jwt:
      secret: 8y/B?E(H+MbQeThWmZq4t6w9z$C&F)J@NcRfUjXn2r5u8x/A%D*G-KaPdSgVkYp3
      expiration: 86400000 # 24 hours in milliseconds

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG
    org.postgresql: DEBUG 